version: 2.1

jobs:
  hello:
    machine: true
    steps:  
      - run: echo 'Hello, world'
      - run: echo 'This is message in CircleCI worker.'
      - run: pwd
      - run: uname -a
      - run: ps
      - run: ls

workflows:
  welcome:
    jobs:
      - hello