version: 2.1

jobs:
  test:
    parameters:
      version:
        type: string
    docker:
      - image: python:<< parameters.version >>
    steps:
      - checkout
      - run: pip install flask pytest
      - run: py.test

workflows:
  welcome:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["3.5", "3.6", "3.7", "2.7"]
